In [1]:
! pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip 

  Using cached https://github.com/pandas-profiling/pandas-profiling/archive/master.zip


In [2]:
!pip install scikit-plot

Import necessary modules and necessary libraries

In [3]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from yellowbrick.cluster import KElbowVisualizer
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import style
import pandas_profiling
from pandas_profiling import ProfileReport
import sklearn
from sklearn import metrics
import scikitplot as skplt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import RocCurveDisplay
from sklearn.metrics import plot_roc_curve
from sklearn.ensemble import VotingClassifier
from sklearn import datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import roc_auc_score
from pandas import DataFrame


Import The dataset into variable called facebook first version

In [4]:
Facebook_first_version = pd.read_csv('CW2_Facebook_metrics.csv')

Understand the data set

In [5]:
Facebook_first_version.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                                                               Non-Null Count  Dtype  
---  ------                                                               --------------  -----  
 0   Page total likes                                                     500 non-null    int64  
 1   Type                                                                 500 non-null    object 
 2   Category                                                             500 non-null    int64  
 3   Post Month                                                           500 non-null    int64  
 4   Post Weekday                                                         500 non-null    int64  
 5   Post Hour                                                            500 non-null    int64  
 6   Paid                                                                 499 non-null    float64
 7   Lifetime

In [6]:
Facebook_first_version.shape

(500, 19)

Profile report to understand the data

In [7]:
report = ProfileReport(Facebook_first_version, title='Pandas Profiling Report Task A dataset CW2', explorative=True)
report.to_file(output_file="CW2_Data_statistics.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
Facebook_first_version.head()

Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0            139441   Photo         2          12             4          3   
1            139441  Status         2          12             3         10   
2            139441   Photo         3          12             3          3   
3            139441   Photo         2          12             2         10   
4            139441   Photo         2          12             2          3   

   Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0   0.0                       2752                             5091   
1   0.0                      10460                            19057   
2   0.0                       2413                             4373   
3   1.0                      50128                            87991   
4   0.0                       7244                            13594   

   Lifetime Engaged Users  Lifetime Post Consumers  \
0                     178                      109   
1                    1457                     1361   
2                     177                      113   
3                    2211                      790   
4                     671                      410   

   Lifetime Post Consumptions  \
0                         159   
1                        1674   
2                         154   
3                        1119   
4                         580   

   Lifetime Post Impressions by people who have liked your Page  \
0                                               3078              
1                                              11710              
2                                               2812              
3                                              61027              
4                                               6228              

   Lifetime Post reach by people who like your Page  \
0                                              1640   
1                                              6112   
2                                              1503   
3                                             32048   
4                                              3200   

   Lifetime People who have liked your Page and engaged with your post  \
0                                                119                     
1                                               1108                     
2                                                132                     
3                                               1386                     
4                                                396                     

   Comments   Likes  Shares  Total Interactions  
0         4    79.0    17.0                 100  
1         5   130.0    29.0                 164  
2         0    66.0    14.0                  80  
3        58  1572.0   147.0                1777  
4        19   325.0    49.0                 393

In [9]:
Facebook_first_version.dtypes

Page total likes                                                         int64
Type                                                                    object
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                                               int64
Lifetime Post Impressions by people who have liked y

In [10]:
Facebook_first_version.describe()

Page total likes    Category  Post Month  Post Weekday   Post Hour  \
count        500.000000  500.000000  500.000000    500.000000  500.000000   
mean      123194.176000    1.880000    7.038000      4.150000    7.840000   
std        16272.813214    0.852675    3.307936      2.030701    4.368589   
min        81370.000000    1.000000    1.000000      1.000000    1.000000   
25%       112676.000000    1.000000    4.000000      2.000000    3.000000   
50%       129600.000000    2.000000    7.000000      4.000000    9.000000   
75%       136393.000000    3.000000   10.000000      6.000000   11.000000   
max       139441.000000    3.000000   12.000000      7.000000   23.000000   

             Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
count  499.000000                  500.00000                     5.000000e+02   
mean     0.278557                13903.36000                     2.958595e+04   
std      0.448739                22740.78789                     7.680325e+04   
min      0.000000                  238.00000                     5.700000e+02   
25%      0.000000                 3315.00000                     5.694750e+03   
50%      0.000000                 5281.00000                     9.051000e+03   
75%      1.000000                13168.00000                     2.208550e+04   
max      1.000000               180480.00000                     1.110282e+06   

       Lifetime Engaged Users  Lifetime Post Consumers  \
count              500.000000               500.000000   
mean               920.344000               798.772000   
std                985.016636               882.505013   
min                  9.000000                 9.000000   
25%                393.750000               332.500000   
50%                625.500000               551.500000   
75%               1062.000000               955.500000   
max              11452.000000             11328.000000   

       Lifetime Post Consumptions  \
count                  500.000000   
mean                  1415.130000   
std                   2000.594118   
min                      9.000000   
25%                    509.250000   
50%                    851.000000   
75%                   1463.000000   
max                  19779.000000   

       Lifetime Post Impressions by people who have liked your Page  \
count                                       5.000000e+02              
mean                                        1.676638e+04              
std                                         5.979102e+04              
min                                         5.670000e+02              
25%                                         3.969750e+03              
50%                                         6.255500e+03              
75%                                         1.486050e+04              
max                                         1.107833e+06              

       Lifetime Post reach by people who like your Page  \
count                                        500.000000   
mean                                        6585.488000   
std                                         7682.009405   
min                                          236.000000   
25%                                         2181.500000   
50%                                         3417.000000   
75%                                         7989.000000   
max                                        51456.000000   

       Lifetime People who have liked your Page and engaged with your post  \
count                                         500.000000                     
mean                                          609.986000                     
std                                           612.725618                     
min                                             9.000000                     
25%                                           291.000000                     
50%                                           412.000000                     
75%     

Understand the number of missing values in each column by the number of them

In [11]:
Facebook_first_version.isna().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page   

Treatment of null values, Dropping them is a good way to treat them based on the amount of null values

In [12]:
Facebook_first_version = Facebook_first_version.dropna()
Facebook_first_version.reset_index(drop=True, inplace=True)
Facebook_first_version.isna().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   0
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page   

Change datatype of Type column to integer

In [13]:
print("Type unique: ", len(Facebook_first_version.Type.unique()))
print(Facebook_first_version["Type"].value_counts())

Type unique:  4
Photo     421
Status     45
Link       22
Video       7
Name: Type, dtype: int64


In [14]:
conditions = [
    (Facebook_first_version["Type"] == 'Photo'),
    (Facebook_first_version["Type"] == 'Status'),
    (Facebook_first_version["Type"] == 'Link'),
    (Facebook_first_version["Type"] == 'Video')
    ]

# create a list of the values we want to assign for each condition
value = [0,1,2,3]
Facebook_first_version['Type to numeric'] = np.select(conditions, value)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.


Check the change datatype of Type column to integer

In [15]:
print("Type unique: ", len(Facebook_first_version['Type to numeric'].unique()))
print(Facebook_first_version['Type to numeric'].value_counts())

Type unique:  4
0    421
1     45
2     22
3      7
Name: Type to numeric, dtype: int64


Another way is Changing data type of Type column into 4 columns and use hot encoding to replace it

In [16]:
pd.get_dummies(Facebook_first_version, columns=["Type"]).head()
Facebook_second_version = pd.get_dummies(Facebook_first_version, columns=["Type"])

Datatype is recovered and lets see if the changes are applied

In [17]:
Facebook_second_version.dtypes

Page total likes                                                         int64
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                                               int64
Lifetime Post Impressions by people who have liked your Page             int64
Lifetime Post reach by people who like your Page    

Treatment of outliers:
First define a boxplot to see every column distribution and see if there is any outliers

In [18]:
def plot_boxplot(dataframe, feature):
  dataframe.boxplot(column=[feature])
  plt.grid(False)
  

In [19]:
for column in  Facebook_second_version.columns:
  plot_boxplot(Facebook_second_version, column)
  plt.grid(False)
  plt.savefig("Boxplot for " + column + ".png")
  plt.show()
  plt.clf()


Create a function for detecting outliers

In [20]:
def outliers(dataframe, feature):
    q1 = dataframe[feature].quantile(0.25)
    q3 = dataframe[feature].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    ls = dataframe.index[ (dataframe[feature] < lower_bound) | (dataframe[feature] > upper_bound) ]
    return ls


Create a list to see the indexes of outliers for second version and also only detect outliers for the columns that are going to be used in analysis

In [21]:
outliers_index_secondV = []
for column in ['Page total likes', 'Category', 'Post Month', 'Post Weekday','Post Hour', 'Paid','Lifetime Post Consumers']:
  outliers_index_secondV.extend(outliers(Facebook_second_version, column))
outliers_index_secondV,len(outliers_index_secondV)

([10,
  26,
  38,
  42,
  46,
  80,
  98,
  105,
  109,
  119,
  138,
  139,
  147,
  164,
  168,
  171,
  179,
  219,
  221,
  238,
  239,
  240,
  249,
  268,
  271,
  275,
  278,
  367,
  375,
  442,
  443,
  445,
  453,
  456,
  460,
  472,
  478],
 37)

Create a function for deleting outliers based on their indexes

In [22]:
def remove(df,ls):
    ls = sorted(set(ls))
    df = df.drop(ls)
    return df
Facebook_second_version_cleaned = remove(Facebook_second_version,outliers_index_secondV)
Facebook_second_version_cleaned.reset_index(drop=True, inplace=True)


See howe many outliers were detected and deleted

In [23]:
print(len(Facebook_second_version_cleaned))
print(len(Facebook_second_version))

458
495


In [24]:
Facebook_second_version_cleaned.describe()

Page total likes    Category  Post Month  Post Weekday   Post Hour  \
count        458.000000  458.000000  458.000000    458.000000  458.000000   
mean      123122.395197    1.901747    7.006550      4.122271    7.799127   
std        16075.297857    0.865809    3.290787      2.035330    4.425785   
min        81370.000000    1.000000    1.000000      1.000000    1.000000   
25%       111972.000000    1.000000    4.000000      2.000000    3.000000   
50%       129600.000000    2.000000    7.000000      4.000000    9.000000   
75%       136393.000000    3.000000   10.000000      6.000000   11.000000   
max       139441.000000    3.000000   12.000000      7.000000   23.000000   

             Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
count  458.000000                 458.000000                     4.580000e+02   
mean     0.272926               11921.794760                     2.519002e+04   
std      0.445950               19131.504289                     6.894823e+04   
min      0.000000                 238.000000                     5.700000e+02   
25%      0.000000                3217.500000                     5.562250e+03   
50%      0.000000                4924.000000                     8.516000e+03   
75%      1.000000               10676.000000                     1.881525e+04   
max      1.000000              153536.000000                     1.110282e+06   

       Lifetime Engaged Users  Lifetime Post Consumers  ...  \
count              458.000000               458.000000  ...   
mean               723.766376               618.711790  ...   
std                481.706008               404.965957  ...   
min                  9.000000                 9.000000  ...   
25%                386.000000               323.250000  ...   
50%                597.000000               522.500000  ...   
75%                949.000000               837.750000  ...   
max               3000.000000              1912.000000  ...   

       Lifetime People who have liked your Page and engaged with your post  \
count                                         458.000000                     
mean                                          486.921397                     
std                                           339.647614                     
min                                             9.000000                     
25%                                           284.000000                     
50%                                           398.000000                     
75%                                           570.000000                     
max                                          1978.000000                     

         Comments        Likes      Shares  Total Interactions  \
count  458.000000   458.000000  458.000000          458.000000   
mean     5.696507   150.545852   23.325328          179.567686   
std      9.671046   196.649437   20.734147          218.514752   
min      0.000000     0.000000    0.000000            0.000000   
25%      1.000000    55.000000   10.000000           70.000000   
50%      2.500000    98.000000   18.000000          119.000000   
75%      6.000000   171.000000   31.000000          210.750000   
max    103.000000  1639.000000  147.000000         1806.000000   

       Type to numeric   Type_Link  Type_Photo  Type_Status  Type_Video  
count       458.000000  458.000000  458.000000   458.000000  458.000000  
mean          0.185590    0.048035    0.884279     0.056769    0.010917  
std           0.559824    0.214074    0.320239     0.231653    0.104026  
min           0.000000    0.000000    0.000000     0.000000    0.000000  
25%           0.000000    0.000000    1.000000     0.000000    0.000000  
50%           0.000000    0.000000    1.000000     0.000000    0.000000  
75%           0.000000    0.000000    1.000000     0.000000    0.000000  
max           3.000000    1.000000    1.000000     1.000000    1.000000  

[8 rows x 23 columns]

Change the outcome vallue(Lifetime Post Consumers) to categorical value with each group having around 50 percent of data. In the data description we can see its 520

In [25]:
conditions1 = [
    (Facebook_second_version_cleaned['Lifetime Post Consumers'] < 520),
    (Facebook_second_version_cleaned['Lifetime Post Consumers'] >= 520)
    ]

# create a list of the values we want to assign for each condition
value1 = [0, 1]


Facebook_second_version_cleaned['Lifetime Post Consumers Categorized'] = np.select(conditions1, value1)

Lets see the number of categorized value of the outcome in the two groups that we created

In [26]:
print("Lifetime Post Consumers : ", len(Facebook_second_version_cleaned['Lifetime Post Consumers Categorized'].unique()))
print(Facebook_second_version_cleaned['Lifetime Post Consumers Categorized'].value_counts())

Lifetime Post Consumers :  2
1    230
0    228
Name: Lifetime Post Consumers Categorized, dtype: int64


Get a glance of the dataset that we want to use for X and y

In [27]:
Facebook_second_version_cleaned

Page total likes  Category  Post Month  Post Weekday  Post Hour  Paid  \
0              139441         2          12             4          3   0.0   
1              139441         2          12             3         10   0.0   
2              139441         3          12             3          3   0.0   
3              139441         2          12             2         10   1.0   
4              139441         2          12             2          3   0.0   
..                ...       ...         ...           ...        ...   ...   
453             85093         3           1             7         10   0.0   
454             85093         3           1             7          2   0.0   
455             81370         2           1             5          8   0.0   
456             81370         1           1             5          2   0.0   
457             81370         3           1             4         11   0.0   

     Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0                         2752                             5091   
1                        10460                            19057   
2                         2413                             4373   
3                        50128                            87991   
4                         7244                            13594   
..                         ...                              ...   
453                       5400                             9218   
454                       4684                             7536   
455                       3480                             6229   
456                       3778                             7216   
457                       4156                             7564   

     Lifetime Engaged Users  Lifetime Post Consumers  ...  Comments   Likes  \
0                       178                      109  ...         4    79.0   
1                      1457                     1361  ...         5   130.0   
2                       177                      113  ...         0    66.0   
3                      2211                      790  ...        58  1572.0   
4                       671                      410  ...        19   325.0   
..                      ...                      ...  ...       ...     ...   
453                     810                      756  ...        10   125.0   
454                     733                      708  ...         5    53.0   
455                     537                      508  ...         0    53.0   
456                     625                      572  ...         4    93.0   
457                     626                      574  ...         7    91.0   

     Shares  Total Interactions  Type to numeric  Type_Link  Type_Photo  \
0      17.0                 100                0          0           1   
1      29.0                 164                1          0           0   
2      14.0                  80                0          0           1   
3     147.0                1777                0          0           1   
4      49.0                 393                0          0           1   
..      ...                 ...              ...        ...         ...   
453    41.0                 176                0          0           1   
454    26.0                  84                0          0           1   
455    22.0                  75                0          0           1   
456    18.0                 115                0          0           1   
457    38.0                 136                0          0           1   

     Type_Status  Type_Video  Lifetime Post Consumers Categorized  
0              0           0                                    0  
1              1           0                                    1  
2              0           0                                    0  
3              0           0                                    1  
4              0           0                                    0  
..   

In [28]:
Facebook_second_version_cleaned.to_csv('CW2_Final dataset before splits to X and y.csv', index=False)

In [29]:
Facebook_second_version_cleaned.columns

Index(['Page total likes', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'Comments', 'Likes', 'Shares', 'Total Interactions', 'Type to numeric',
       'Type_Link', 'Type_Photo', 'Type_Status', 'Type_Video',
       'Lifetime Post Consumers Categorized'],
      dtype='object')

Split the data into input and output with two ways

First way for spliting the data:

In [30]:
feature_cols_for_input=['Page total likes','Category','Post Month','Post Weekday','Post Hour','Paid','Type to numeric']
X = Facebook_second_version_cleaned[feature_cols_for_input]
y = Facebook_second_version_cleaned['Lifetime Post Consumers Categorized']

In [31]:
X

Page total likes  Category  Post Month  Post Weekday  Post Hour  Paid  \
0              139441         2          12             4          3   0.0   
1              139441         2          12             3         10   0.0   
2              139441         3          12             3          3   0.0   
3              139441         2          12             2         10   1.0   
4              139441         2          12             2          3   0.0   
..                ...       ...         ...           ...        ...   ...   
453             85093         3           1             7         10   0.0   
454             85093         3           1             7          2   0.0   
455             81370         2           1             5          8   0.0   
456             81370         1           1             5          2   0.0   
457             81370         3           1             4         11   0.0   

     Type to numeric  
0                  0  
1                  1  
2                  0  
3                  0  
4                  0  
..               ...  
453                0  
454                0  
455                0  
456                0  
457                0  

[458 rows x 7 columns]

In [32]:
y

0      0
1      1
2      0
3      1
4      0
      ..
453    1
454    1
455    0
456    1
457    1
Name: Lifetime Post Consumers Categorized, Length: 458, dtype: int64

Second way for spliting the data:

In [33]:
X = Facebook_second_version_cleaned.drop(columns=['Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'Comments', 'Likes', 'Shares', 'Total Interactions',
       'Type_Link', 'Type_Photo', 'Type_Status', 'Type_Video',
       'Lifetime Post Consumers Categorized'])
y = Facebook_second_version_cleaned['Lifetime Post Consumers Categorized']

In [34]:
X

Page total likes  Category  Post Month  Post Weekday  Post Hour  Paid  \
0              139441         2          12             4          3   0.0   
1              139441         2          12             3         10   0.0   
2              139441         3          12             3          3   0.0   
3              139441         2          12             2         10   1.0   
4              139441         2          12             2          3   0.0   
..                ...       ...         ...           ...        ...   ...   
453             85093         3           1             7         10   0.0   
454             85093         3           1             7          2   0.0   
455             81370         2           1             5          8   0.0   
456             81370         1           1             5          2   0.0   
457             81370         3           1             4         11   0.0   

     Type to numeric  
0                  0  
1                  1  
2                  0  
3                  0  
4                  0  
..               ...  
453                0  
454                0  
455                0  
456                0  
457                0  

[458 rows x 7 columns]

In [35]:
y

0      0
1      1
2      0
3      1
4      0
      ..
453    1
454    1
455    0
456    1
457    1
Name: Lifetime Post Consumers Categorized, Length: 458, dtype: int64

Scaling the input before doing analysis

In [36]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

Split input and output into training and testing data set with holdout method

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=1,stratify=y)

Split the data with the help of K-fold method

In [38]:

kf= KFold(n_splits=5)
kf.get_n_splits(X)
print(kf)
KFold(n_splits=10, random_state=None,shuffle=False)
for train_index, test_index in kf.split(X):
  print("TRAIN:", train_index, "TEST", test_index)
  X_train_kfold, X_test_kfold= X_scaled[train_index], X_scaled[test_index]
  y_train_kfold, y_test_kfold= y[train_index], y[test_index]

KFold(n_splits=5, random_state=None, shuffle=False)
TRAIN: [ 92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199
 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253
 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271
 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289
 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307
 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 

Building our models

First Building the KNN classifier

In [39]:
knn_model = KNeighborsClassifier(n_neighbors=3)
# Train the model
knn_model.fit(X_train, y_train)
#predict test data
y_pred_knn = knn_model.predict(X_test)

Check the scores of our KNN classifier

In [40]:
knn_score = accuracy_score(y_test, y_pred_knn)
print("Accuracy score (KNN): ", knn_score)
print("Precision (KNN): ", metrics.precision_score(y_test,y_pred_knn))
print("Recal(KNN): ", metrics.recall_score(y_test,y_pred_knn))

Accuracy score (KNN):  0.7608695652173914
Precision (KNN):  0.7571428571428571
Recal(KNN):  0.7681159420289855


Lets see the confusion metrics for KNN model

In [41]:
cm1 = confusion_matrix(y_test, y_pred_knn)
cm1

array([[52, 17],
       [16, 53]])

knn classification report

In [42]:
print(classification_report(y_test, y_pred_knn)) 

              precision    recall  f1-score   support

           0       0.76      0.75      0.76        69
           1       0.76      0.77      0.76        69

    accuracy                           0.76       138
   macro avg       0.76      0.76      0.76       138
weighted avg       0.76      0.76      0.76       138



Now lets create our KNN model and get all the reports with the K-fold test and train data

In [43]:
knn_model_with_kfold = KNeighborsClassifier(n_neighbors=3)
# Train the model
knn_model_with_kfold.fit(X_train_kfold, y_train_kfold)
#predict test data
y_pred_knn_kfold = knn_model_with_kfold.predict(X_test_kfold)
knn_score_kfold = accuracy_score(y_test_kfold, y_pred_knn_kfold)
print("Accuracy score with kfold split (KNN): ", knn_score_kfold)

Accuracy score with kfold split (KNN):  0.7032967032967034


Now lets do the same for our logistic regression clasifier

Create and fit the model and predict the output for the test data

In [44]:
log_model = LogisticRegression()
log_model.fit(X_train, y_train)
y_pred_log = log_model.predict(X_test)

Check the scores of our logistic regression classifier

In [45]:
log_score = accuracy_score(y_test, y_pred_log)
print("Accuracy score (Logistic): ", log_score)
print("Precision (Logistic): ", metrics.precision_score(y_test,y_pred_log))
print("Recal(Logistic): ", metrics.recall_score(y_test,y_pred_log))

Accuracy score (Logistic):  0.7536231884057971
Precision (Logistic):  0.7464788732394366
Recal(Logistic):  0.7681159420289855


Lets see the confusion metrics for Logistic regression model

In [46]:
cm2 = confusion_matrix(y_test, y_pred_log)
cm2

array([[51, 18],
       [16, 53]])

Logistic regression model classification report

In [47]:
print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

           0       0.76      0.74      0.75        69
           1       0.75      0.77      0.76        69

    accuracy                           0.75       138
   macro avg       0.75      0.75      0.75       138
weighted avg       0.75      0.75      0.75       138



See the accuracy with kfold inputs

In [48]:
log_model_with_kfold =LogisticRegression()
# Train the model
log_model_with_kfold.fit(X_train_kfold, y_train_kfold)
#predict test data
y_pred_log_kfold = log_model_with_kfold.predict(X_test_kfold)
log_score_kfold = accuracy_score(y_test_kfold, y_pred_log_kfold)
print("Accuracy score with kfold split (Logistic): ", log_score_kfold)

Accuracy score with kfold split (Logistic):  0.6703296703296703


Lets create our third classifier and use Support vector machine this time

Create and fit the model and predict the output for the test data

First we use polynomial kernel

In [77]:
svm_model_poly = SVC(kernel='poly',probability=True)
svm_model_poly.fit(X_train, y_train)
y_pred_svm_poly = svm_model_poly.predict(X_test)

Check the scores of our Support vector machine classifier

In [79]:
svm_score_poly = accuracy_score(y_test, y_pred_svm_poly)
print("Accuracy score (SVM_POLY): ", svm_score_poly)
print("Precision (SVM_POLY): ", metrics.precision_score(y_test,y_pred_svm_poly))
print("Recal(SVM_POLY): ", metrics.recall_score(y_test,y_pred_svm_poly))

Accuracy score (SVM_POLY):  0.7536231884057971
Precision (SVM_POLY):  0.7536231884057971
Recal(SVM_POLY):  0.7536231884057971


Lets see the confusion metrics for Support vector machine model

In [80]:
cm3_poly = confusion_matrix(y_test, y_pred_svm_poly)
cm3_poly

array([[52, 17],
       [17, 52]])

Support vector machine model classification report




In [81]:
print(classification_report(y_test, y_pred_svm_poly))

              precision    recall  f1-score   support

           0       0.75      0.75      0.75        69
           1       0.75      0.75      0.75        69

    accuracy                           0.75       138
   macro avg       0.75      0.75      0.75       138
weighted avg       0.75      0.75      0.75       138



This time using Guassian kernel for SVM

In [83]:
svm_model_Guassian = SVC(kernel='rbf',probability=True)
svm_model_Guassian.fit(X_train, y_train)
y_pred_svm_Guassian = svm_model_Guassian.predict(X_test)
svm_score_Guassian = accuracy_score(y_test, y_pred_svm_Guassian)
print("Accuracy score (SVM_Guassian): ", svm_score_Guassian)
print("Precision (SVM_Guassian): ", metrics.precision_score(y_test,y_pred_svm_Guassian))
print("Recal(SVM_Guassian): ", metrics.recall_score(y_test,y_pred_svm_Guassian))
cm3_Guassian = confusion_matrix(y_test, y_pred_svm_Guassian)
print(cm3_Guassian)
print(classification_report(y_test, y_pred_svm_Guassian))

Accuracy score (SVM_Guassian):  0.8043478260869565
Precision (SVM_Guassian):  0.8
Recal(SVM_Guassian):  0.8115942028985508
[[55 14]
 [13 56]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.80        69
           1       0.80      0.81      0.81        69

    accuracy                           0.80       138
   macro avg       0.80      0.80      0.80       138
weighted avg       0.80      0.80      0.80       138



Now lets use sigmoid kernel

In [84]:
svm_model_Sigmoid = SVC(kernel='sigmoid',probability=True)
svm_model_Sigmoid.fit(X_train, y_train)
y_pred_svm_Sigmoid = svm_model_Sigmoid.predict(X_test)
svm_score_Sigmoid = accuracy_score(y_test, y_pred_svm_Sigmoid)
print("Accuracy score (SVM_Sigmoid): ", svm_score_Sigmoid)
print("Precision (SVM_Sigmoid): ", metrics.precision_score(y_test,y_pred_svm_Sigmoid))
print("Recal(SVM_Sigmoid): ", metrics.recall_score(y_test,y_pred_svm_Sigmoid))
cm3_Sigmoid = confusion_matrix(y_test, y_pred_svm_Sigmoid)
print(cm3_Sigmoid)
print(classification_report(y_test, y_pred_svm_Sigmoid))

Accuracy score (SVM_Sigmoid):  0.7391304347826086
Precision (SVM_Sigmoid):  0.7704918032786885
Recal(SVM_Sigmoid):  0.6811594202898551
[[55 14]
 [22 47]]
              precision    recall  f1-score   support

           0       0.71      0.80      0.75        69
           1       0.77      0.68      0.72        69

    accuracy                           0.74       138
   macro avg       0.74      0.74      0.74       138
weighted avg       0.74      0.74      0.74       138



See the accuracy with kfold inputs

In [85]:
svm_model_Guassian_with_kfold =SVC(kernel='rbf',probability=True)
# Train the model
svm_model_Guassian_with_kfold .fit(X_train_kfold, y_train_kfold)
#predict test data
y_pred_svm_Guassian_kfold = svm_model_Guassian_with_kfold.predict(X_test_kfold)
svm_score_kfold = accuracy_score(y_test_kfold, y_pred_svm_Guassian_kfold)
print("Accuracy score with kfold split (SVM-Guassian): ", svm_score_kfold)

Accuracy score with kfold split (SVM-Guassian):  0.6703296703296703


Lets create our last classifier the randomforest

Create and fit the model and predict the output for the test data

In [56]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

Check the scores of our randomforest classifier

In [57]:
rf_score = accuracy_score(y_test, y_pred_rf)
print("Accuracy score (Random Forest): ", rf_score)
print("Precision (Random Forest): ", metrics.precision_score(y_test,y_pred_rf))
print("Recal(Random Forest): ", metrics.recall_score(y_test,y_pred_rf))

Accuracy score (Random Forest):  0.7971014492753623
Precision (Random Forest):  0.8153846153846154
Recal(Random Forest):  0.7681159420289855


Lets see the confusion metrics for Random Forest model

In [58]:
cm4 = confusion_matrix(y_test, y_pred_rf)
cm4

array([[57, 12],
       [16, 53]])

Random Forest model classification report

In [59]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.78      0.83      0.80        69
           1       0.82      0.77      0.79        69

    accuracy                           0.80       138
   macro avg       0.80      0.80      0.80       138
weighted avg       0.80      0.80      0.80       138



See the accuracy with kfold inputs

In [60]:
rf_model_with_kfold =RandomForestClassifier()
# Train the model
rf_model_with_kfold.fit(X_train_kfold, y_train_kfold)
#predict test data
y_pred_rf_kfold = rf_model_with_kfold.predict(X_test_kfold)
rf_score_kfold = accuracy_score(y_test_kfold, y_pred_rf_kfold)
print("Accuracy score with kfold split Random Forest): ", rf_score_kfold)

Accuracy score with kfold split Random Forest):  0.6813186813186813


Now before we create our voting classifier lets see the accuracy of each classifier with holdout method

In [90]:
print("Accuracy score (KNN): ", knn_score)
print("Accuracy score (Logistic): ", log_score)
print("Accuracy score (Random Forest): ", rf_score)
print("Accuracy score (SVM_Guassian): ", svm_score_Guassian)

Accuracy score (KNN):  0.7608695652173914
Accuracy score (Logistic):  0.7536231884057971
Accuracy score (Random Forest):  0.7971014492753623
Accuracy score (SVM_Guassian):  0.8043478260869565


Lets see the accuracy with kfold method too

In [89]:
print("Accuracy score with kfold split (KNN with kfold): ", knn_score_kfold)
print("Accuracy score with kfold split (Logistic with kfold): ", log_score_kfold)
print("Accuracy score with kfold split (SVM-Guassian with kfold): ", svm_score_kfold)
print("Accuracy score with kfold split Random Forest with kfold): ", rf_score_kfold)

Accuracy score with kfold split (KNN with kfold):  0.7032967032967034
Accuracy score with kfold split (Logistic with kfold):  0.6703296703296703
Accuracy score with kfold split (SVM-Guassian with kfold):  0.6703296703296703
Accuracy score with kfold split Random Forest with kfold):  0.6813186813186813


Create our ensemble voting classifier

First create a dictionary of our models

In [87]:
#create a dictionary of our models
estimators=[('knn', knn_model), ('rf', rf_model), ('log_reg', log_model),('svm',svm_model_Guassian)]
#create our voting classifier, inputting our models
ensemble = VotingClassifier(estimators, voting='soft')
#fit model to training data
ensemble.fit(X_train, y_train)
#test our model on the test data
y_pred_ensemble = ensemble.predict(X_test)

Check the scores of our voting classifier

In [92]:
ensemble_score = accuracy_score(y_test, y_pred_ensemble)
print("Accuracy score (Ensemble): ", ensemble_score)
print("Precision (Ensemble): ", metrics.precision_score(y_test,y_pred_ensemble))
print("Recal(Ensemble): ", metrics.recall_score(y_test,y_pred_ensemble))

Accuracy score (Ensemble):  0.8115942028985508
Precision (Ensemble):  0.8028169014084507
Recal(Ensemble):  0.8260869565217391


Lets see the confusion metrics for voting classifier

In [93]:
cm5 = confusion_matrix(y_test, y_pred_ensemble)
cm5

array([[55, 14],
       [12, 57]])

voting classifier model classification report

In [94]:
print(classification_report(y_test, y_pred_ensemble))

              precision    recall  f1-score   support

           0       0.82      0.80      0.81        69
           1       0.80      0.83      0.81        69

    accuracy                           0.81       138
   macro avg       0.81      0.81      0.81       138
weighted avg       0.81      0.81      0.81       138



Now lets see the voting classifier with kfold

Builld the model

In [95]:
#create a dictionary of our models
estimators_with_kfold=[('knn', knn_model_with_kfold), ('rf', rf_model_with_kfold), ('log_reg', log_model_with_kfold),('svm',svm_model_Guassian_with_kfold)]
#create our voting classifier, inputting our models
ensemble_with_kfold = VotingClassifier(estimators_with_kfold, voting='soft')
#fit model to training data
ensemble_with_kfold.fit(X_train_kfold, y_train_kfold)
#test our model on the test data
y_pred_ensemble_with_kfold = ensemble_with_kfold.predict(X_test)

Build the data to see how ell the model is predicting

In [96]:
ensemble_score_with_kfold = accuracy_score(y_test, y_pred_ensemble_with_kfold)
print("Accuracy score (Ensemble with kfold): ", ensemble_score_with_kfold)
print("Precision (Ensemble with kfold): ", metrics.precision_score(y_test,y_pred_ensemble_with_kfold))
print("Recal(Ensemble with kfold): ", metrics.recall_score(y_test,y_pred_ensemble_with_kfold))
cm5_with_kfold = confusion_matrix(y_test, y_pred_ensemble_with_kfold)
print(cm5_with_kfold)
print(classification_report(y_test, y_pred_ensemble_with_kfold))

Accuracy score (Ensemble with kfold):  0.8768115942028986
Precision (Ensemble with kfold):  0.8513513513513513
Recal(Ensemble with kfold):  0.9130434782608695
[[58 11]
 [ 6 63]]
              precision    recall  f1-score   support

           0       0.91      0.84      0.87        69
           1       0.85      0.91      0.88        69

    accuracy                           0.88       138
   macro avg       0.88      0.88      0.88       138
weighted avg       0.88      0.88      0.88       138



Now we created all of our classifiers and ensemble we want to tune our classifiers for better answer. So we have to do all of the things that we have done but use grid search in each classifier and use a range of different values for hyperparameters of classifiers and find the best one for each classifier. Then use the best ones of each classifier in our final ensemble voting classifier

First create grid serach for the knn model

In [97]:
#create a dictionary of all values we want to test for n_neighbors
knn = KNeighborsClassifier()
#use gridsearch to test all values for n_neighbors
params_knn = {'n_neighbors': np.arange(1, 25)} 
#fit model to training data
knn_gs = GridSearchCV(knn, params_knn, cv=5)
knn_gs.fit(X_train, y_train)
#save best model
knn_best = knn_gs.best_estimator_
#check best n_neigbors value
print(knn_gs.best_params_)
y_pred_knn_GS = knn_best.predict(X_test)
knn_score_GS = accuracy_score(y_test, y_pred_knn_GS)
print("Accuracy score with Grid Search (KNN): ", knn_score_GS)
cm1_GS = confusion_matrix(y_test, y_pred_knn_GS)
print(cm1_GS)
# knn classification report with grid search
print(classification_report(y_test, y_pred_knn_GS)) 

{'n_neighbors': 7}
Accuracy score with Grid Search (KNN):  0.782608695652174
[[56 13]
 [17 52]]
              precision    recall  f1-score   support

           0       0.77      0.81      0.79        69
           1       0.80      0.75      0.78        69

    accuracy                           0.78       138
   macro avg       0.78      0.78      0.78       138
weighted avg       0.78      0.78      0.78       138



Grid search on support vector machine

In [98]:
svm= SVC(kernel='rbf',probability=True)
params_svm = {'C':[0.01,0.1,1,10,100,1000], 'gamma':[1,0.1,0.01,0.001,0.0001]}
#fit model to training data
svm_gs = GridSearchCV(svm, params_svm, cv=5)
svm_gs.fit(X_train, y_train)
#save best model
svm_best = svm_gs.best_estimator_
#check best n_estimators value
print(svm_gs.best_params_)
y_pred_svm_GS = svm_best.predict(X_test)
svm_score_GS = accuracy_score(y_test, y_pred_svm_GS)
print("Accuracy score with Grid Search (SVM): ", svm_score_GS)
cm2_GS= confusion_matrix(y_test, y_pred_svm_GS)
print(cm2_GS)
# svm classification report
print(classification_report(y_test, y_pred_svm_GS)) 



{'C': 1, 'gamma': 0.1}
Accuracy score with Grid Search (SVM):  0.8260869565217391
[[56 13]
 [11 58]]
              precision    recall  f1-score   support

           0       0.84      0.81      0.82        69
           1       0.82      0.84      0.83        69

    accuracy                           0.83       138
   macro avg       0.83      0.83      0.83       138
weighted avg       0.83      0.83      0.83       138



Grid search on logistic regression

In [99]:
log_reg = LogisticRegression()#fit the model to the training data
log_reg.fit(X_train, y_train)
#use gridsearch to test different values 
params_log = {'C':[0.001,0.01,0.1,1,10,100,1000],'penalty':['l1', 'l2', 'elasticnet']}
#fit model to training data
log_gs = GridSearchCV(log_reg, params_log, cv=5)
log_gs.fit(X_train, y_train)
#save best model
log_best = knn_gs.best_estimator_
#check best n_estimators value
print(log_gs.best_params_)
y_pred_log_GS = log_best.predict(X_test)
log_score_GS = accuracy_score(y_test, y_pred_log_GS)
print("Accuracy score with Grid Search (Logistic Regression): ", log_score_GS)
cm2_GS = confusion_matrix(y_test, y_pred_log_GS)
print(cm2_GS)
# log classification report with grid search
print(classification_report(y_test, y_pred_log_GS)) 

{'C': 1, 'penalty': 'l2'}
Accuracy score with Grid Search (Logistic Regression):  0.782608695652174
[[56 13]
 [17 52]]
              precision    recall  f1-score   support

           0       0.77      0.81      0.79        69
           1       0.80      0.75      0.78        69

    accuracy                           0.78       138
   macro avg       0.78      0.78      0.78       138
weighted avg       0.78      0.78      0.78       138



/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
70 fits failed out of a total of 105.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solve

Grid search on random forest

In [103]:
rf = RandomForestClassifier()
#create a dictionary of all values we want to test for n_estimators
params_rf = {'n_estimators': [25,50, 100, 200]}
#use gridsearch to test all values for n_estimators
#fit model to training data
rf_gs = GridSearchCV(rf, params_rf, cv=5)
rf_gs.fit(X_train, y_train)
#save best model
rf_best = rf_gs.best_estimator_
#check best n_estimators value
print(rf_gs.best_params_)
y_pred_rf_GS = rf_best.predict(X_test)
rf_score_GS = accuracy_score(y_test, y_pred_rf_GS)
print("Accuracy score with Grid Search (Random Forest): ", rf_score_GS)
cm4_GS = confusion_matrix(y_test, y_pred_rf_GS)
print(cm4_GS)
# random forest classification report
print(classification_report(y_test, y_pred_rf_GS)) 

{'n_estimators': 200}
Accuracy score with Grid Search (Random Forest):  0.7753623188405797
[[56 13]
 [18 51]]
              precision    recall  f1-score   support

           0       0.76      0.81      0.78        69
           1       0.80      0.74      0.77        69

    accuracy                           0.78       138
   macro avg       0.78      0.78      0.78       138
weighted avg       0.78      0.78      0.78       138



Now we use grid search on our ensemble

In [104]:
from sklearn.metrics import RocCurveDisplay
#create a dictionary of our models
estimators_with_GS =[('knn', knn_best), ('rf', rf_best), ('log_reg', log_reg),('svm',svm_best)]
#create our voting classifier, inputting our models
ensemble_with_GS = VotingClassifier(estimators_with_GS , voting='soft')
#fit model to training data
ensemble_with_GS.fit(X_train, y_train)
#test our model on the test data
y_pred_ensemble_with_GS = ensemble_with_GS.predict(X_test)
ensemble_score_with_GS = accuracy_score(y_test, y_pred_ensemble_with_GS)
print("Accuracy score with grid search (Ensemble): ", ensemble_score_with_GS)
cm5_gs = confusion_matrix(y_test, y_pred_ensemble_with_GS)
print(cm5)
# ensemble classification report
print(classification_report(y_test, y_pred_ensemble_with_GS)) 
# Plot ROC Curve
plt.clf()
y_probas_ensemble_GS = ensemble_with_GS.predict_proba(X_test)
skplt.metrics.plot_roc(y_test, y_probas_ensemble_GS, figsize=(10, 8))   
#plot_roc_curve(ensemble_with_GS, X_test, y_test)
plt.savefig('CW2_roc_ensemble_with_Gridsearch.png', dpi=1050)
plt.show()



Accuracy score with grid search (Ensemble):  0.8188405797101449
[[55 14]
 [12 57]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82        69
           1       0.82      0.81      0.82        69

    accuracy                           0.82       138
   macro avg       0.82      0.82      0.82       138
weighted avg       0.82      0.82      0.82       138

